theme: jekyll-theme-cayman
title: Mélissa Mérat
description: Recherche alternance en gestion de projet MOA <br/> Etudiante en M1 MIAGE à l'université de Nantes <br/> description: Motivée, dynamique, efficace et responsable  


