theme: jekyll-theme-cayman
title: Mélissa Mérat
description: Recherche alternance en gestion de projet MOA  
Etudiante en M1 MIAGE à l'université de Nantes
Motivée, dynamique, efficace et responsable  


